//API 1
//user registration 
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}

###
//API 2
//USER LOGIN
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}


###
//API 3
//change Password 
PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}